### ISSUE TITLE
List input parameters one per line in log file 

### ISSUE THREAD

**Issue by dkav** [linkagescape/linkage-mapper#101]
Tool input parameters are currently reported in log files as:
```
Parameters:	['C:\\Users\\Sandeep\\Desktop\\Sumatra_GIS\\Linkage_Mapper_2_0_0\\Linkage_Mapper_2_0_0\\toolbox\\scripts\\lm_master.py', 'C:\\Users\\Sandeep\\Desktop\\BarrierMappingNew', 'SourceTest', 'Source', 'clipped_rast1.tif', 'true', 'true', 'Cost-Weighted & Euclidean', 'C:\\Users\\Sandeep\\Desktop\\BarrierMappingNew\\distances_SourceTest.txt', 'true', 'true', 'false', '4', 'Cost-Weighted', 'true', 'true', 'true', '200000', '#', '#', '#', '#', '#'] 
```

For clarity, list in a manner something like this:
```
Input Parameters

PROJECT DIR: C:\\Users\\Sandeep\\Desktop\\BarrierMappingNew
CORE LAYER: SourceTest
RESISTANCE LAYER: clipped_rast1.tif
...
```

**Comment by johngallo** [comment]
Excellent idea! and low hanging fruit.
It may be worth using comma separated values, so it can be pasted into a
spreadsheet quickly. Then the second column can be pasted into a master
spreadsheet for the project.  I use such spreadsheets for projects.  The
top row is usually the Project directory name, and I usually make a new
directory for each model run so I compile a suite of outputs to compare.
Would be happy to share such a spreadsheet.  The rows are all the most
important parameters, from all the tools I'm using.



John Gallo, Ph.D.
Senior Scientist
Conservation Biology Institute <https://consbio.org/people/staff/john-gallo>
136 SW Washington Avenue, Suite 202
Corvallis, OR 97333
Remote Office: Inglenook, CA
Phone: 707.962.9078
Twitter: @johnagallo <https://twitter.com/johnagallo>
Updates: Action Research Newsletter
<https://consbio.us9.list-manage.com/subscribe?u=3dea159e4cbe0a0ff3b43eadd&id=e3bd82fd81>

**Comment by johngallo** [comment]
To meet the important use case I outlined above, the example would look like this:

Input Parameters (csv)

PROJECT DIR,C:\\Users\\Sandeep\\Desktop\\BarrierMappingNew
CORE LAYER,SourceTest
RESISTANCE LAYER,clipped_rast1.tif
...

If that is too ugly, I can add a search and replace to my workflow of getting this into a master table, Making it 7 steps instead of 6. Since : is already used by directory path values, making search and replace problematic, we can use =  as follows

Input Parameters (csv)

PROJECT DIR = C:\\Users\\Sandeep\\Desktop\\BarrierMappingNew
CORE LAYER = SourceTest
RESISTANCE LAYER = clipped_rast1.tif

I'm happy with either one.

**Comment by dkav** [comment]
My vote is still for colon space. I find it more readable. That said, @johngallo you can use any delimiter for your user case. Just use the Text to Columns feature. See [Excel 2013 – How to paste comma-separated values](https://www.itsupportguides.com/knowledge-base/office-2013/excel-2013-how-to-paste-comma-separated-values/).

**Comment by johngallo** [comment]
I realized after I made that last post that colon space will work just as
well as  space equalsign space  in the use case.  I'll just use the search
and replace for colonspace, not colon.  So yes, we are in consensus that
colon space is the best delimiter.  Thanks Darren.
