### ISSUE TITLE
Provide more informational data in log file

### ISSUE THREAD

**Issue by dkav** [linkagescape/linkage-mapper#102]
Updating logging to provide more information could help identify problems more efficiently. For example, we could report coordinate systems for inputs, number of cores, cell units, no of cells, ArcGIS version, etc. The current logging system reports a lot of processing info, some of which is not useful after the model run has completed.

**Comment by johngallo** [comment]
Yes, that would be another great addition to the log file.  It would also
be nice to know the GB of RAMand maybe even the processor. And the OS.  And
the version of Arc.  But is any or all of that an invasion of privacy?
Arguably no, since we do not need to share our log files.   Thanks Darren!


John Gallo, Ph.D.
Senior Scientist
Conservation Biology Institute <https://consbio.org/people/staff/john-gallo>
136 SW Washington Avenue, Suite 202
Corvallis, OR 97333
Remote Office: Inglenook, CA
Phone: 707.962.9078
Twitter: @johnagallo <https://twitter.com/johnagallo>
Updates: Action Research Newsletter
<https://consbio.us9.list-manage.com/subscribe?u=3dea159e4cbe0a0ff3b43eadd&id=e3bd82fd81>
