### ISSUE TITLE
Geoprocessing error on **line 858** of s3_calcCwds.py in Linkage Mapper Version 2.0.0

### ISSUE THREAD

**Issue by akeister** [linkagescape/linkage-mapper#107]
Hello,

I keep getting the following error when running the build network and map linkages tool using ArcCatalog 10.7.1. The error always happens when it starts cost distance calculations on the first core. I can get past this step when I test on a small sample area. However, when I load my full data, I keep getting this error. I have 651 GB free space on my drive. When running it hovers around 50% CPU and 20% memory, a lot, but not maxing out.

Interestingly, I can get past this step (using same full input data) on an old machine running 10.4. However, that machine is too slow to process my entire full area (looks like it will take multiple weeks to finish on the entire area). Things are running much faster on my newer machine running 10.7.1 when I run it on the small test area, but when I load the full data, I get this error.

Thanks in advance for any tips!

~Amy

Here is the point in the run where the first error occurs:

Geoprocessing error on **line 858** of s3_calcCwds.py in Linkage Mapper Version 2.0.0:
 
---------------------------------
ERROR 999999: Error executing function.
Failed to execute (GetRasterProperties).

---------------------------------

********************************************************
NOTE: Linkage Mapper tools often work best when run  from ArcCatalog instead of ArcMap. 

Stop time:		Tue Jun 30 17:31:11 2020 

 
---------------------------------
***Problem encountered executing statement:
"test_for_intermediate_core"
The following ArcGIS error is being reported on line line 778 of "C:\Linkage_Mapper_2_0_0\toolbox\scripts\s3_calcCwds.py":
ERROR 999999: Error executing function.
Failed to execute (GetRasterProperties).

[2020_6_30_1421_Linkage Mapper.txt](https://github.com/linkagescape/linkage-mapper/files/4855444/2020_6_30_1421_Linkage.Mapper.txt)

**Comment by johngallo** [comment]
Hello, 

Interesting that it gets past this issue with 10.4 and not with Arc 10.7.1 . Because of this, this might be a question best answered by @dkav , but he is out for a while while he moves houses. For now, I see two clues:

1: "ERROR 000871: Output backlink raster: Unable to delete the output C:\LM_L2\scratch\core5\BACK"

and 2: large filename for  MosaicLinearRescale1SecuredTNCHub0_Rg8_gt22482_Rg8_HubsD_Buff

I would start by making a new project directory like C:\\LM\v1   .  That way you know it is not Arc having a hard time overwriting old files.

If that does nt work, I would make a C:\\LM\v2, and make a copy of your input but with a smaller name.

Please let us know if either of those worked or not. 

Thanks,

John

**Comment by dkav** [comment]
It is almost impossible to track generic ArcGIS errors without original data. Closing on this basis.
