### ISSUE TITLE
Linkage Mapper Toolbox Not working in ArcPro 3.0

### ISSUE THREAD

**Issue by johngallo** [linkagescape/linkage-mapper#166]
LM works in all the other previous versions of ArcPro though.  Wait for v 3.1 to come out to see if issue fixes itself, otherwise needs fixing.

See community dialog from a month or so ago for exact issue.

**Comment by ruborlado** [comment]
I have this issue (Images ) in relation with build network and Map Linkages, ERROR: It looks like decimals are indicated by commas instead of decimal points.





Try changing your Windows Regional and Language settings to English (United States)
or another convention that uses decimal points.
I've tried to change the Lenguage setting  and when try again the tool  a new error appear  , perhaps  posibble  generate by  the Python  configuration. 
Someone with the same issue or idea ?

**Comment by johngallo** [comment]
Solved thanks to community ID of problem and the coded fix by @dkav
