### ISSUE TITLE
Demo core data includes new LP fields

### ISSUE THREAD

**Issue by dkav** [linkagescape/linkage-mapper#62]
I noticed that the demo core data (both core.shp and LP_Demo_Modoc.gdb/cores) includes new LP fields, presumably added during a test run. I would suggest that demo data should not include data derived during a model run.

**Comment by venkanna37** [comment]
is core_id field enough in both files?

**Comment by johngallo** [comment]
Yes.  Good question. And you can double check with Darren, but this seems like a fix that can happen in time for this Version 3 release that is coming soon.  In other words, if you do this soon, I would recommend doing it as a pull request onto this branch https://github.com/linkagescape/linkage-mapper/tree/arcgis-pro , rather than the develop branch.  I believe the plan is to merge the arcgis-pro branch into the master branch right before we publish v 3.0

**Comment by dkav** [comment]
This is fixed in unmerged code. I added a reference to the issue in the commit description, so the issue will close when the commit is merged.

**Comment by dkav** [comment]
The issue highlights that core input data is being modified by LP and I am not sure that is necessarily a good idea. Is there a business case what we are doing this instead of writing a separate output file?

**Comment by johngallo** [comment]
I don't think so. If Randal had a reason for this I forget it.  I cannot imagine one.  I think a separate output file would be a good improvement, just has not risen to the level of a dev issue yet.
