### ISSUE TITLE
Making LM compatible with ArcGIS Pro

### ISSUE THREAD

**Issue by PerleCharlot** [linkagescape/linkage-mapper#76]
Some thoughts and attempts to run LM under Python 3 in ArcGIS Pro:
https://groups.google.com/forum/#!topic/linkage-mapper/0s8xfpdLGHU

**Comment by johngallo** [comment]
Great!  Thanks Perle.  Ok, lets stay in touch about this. Cheers!

**Comment by johngallo** [comment]
The key message form that thread, from Perle: 

**Hi Ross,


Have you checked your Python version of ArcGIS Pro? It probably runs under Python 3 yet that toolbox has been written under Python 2. There are plenty of differences between Python 2 and 3; the Syntax Error you got here is a good example: instead of "exec statement" under Python 2, you'd now have to write "exec(statement)".
I have the same problems as you because I try to run Linkage Mapper on ArcGIS Pro (to avoid memory issues). First step I'd recommend is to check all the scripts with 2to3 command (https://docs.python.org/2/library/2to3.html) which spots basic syntax errors and then you have to manually fix them. Then, you'll also need to make GRASS working under Python 3, considering that there is an unstable version (GRASS 7.7) built to support Python 3 (https://lists.osgeo.org/pipermail/discuss/2019-January/038218.html). So far I'm stuck on switching to that version of GRASS and can't go any further.
Has someone already managed to get Linkage Mapper working under Python 3?
Thanks

Perle**

**Comment by johngallo** [comment]
Arc Pro Distance Functions are here: https://www.esri.com/arcgis-blog/products/arcgis-pro/analytics/whats-new-in-the-spatial-analyst-distance-toolset-in-pro-25/

**Comment by dkav** [comment]
Made compatible in 24679fa6ff0cf6047a92276d6c73f851f1406518.
